language: python
python:
- 2.7
- 3.4
- 3.5
install:
- pip install pytest pytest-pep8 pytest-cov
- pip install coveralls
- pip install codeclimate-test-reporter
script:
- py.test
after_success:
- coveralls
- CODECLIMATE_REPO_TOKEN=974dea7b78bc2217d6adb46f5e9fb545f73369b69cca26fec65ede756417bd1b codeclimate-test-reporter
